### ISSUE TITLE
[FEATURE] Badge for specific system version

### ISSUE THREAD

**Issue by ccjmk** [vigoren/foundryvtt-shields-io-badge#13]
**Is your feature request related to a problem? Please describe.**
It is not rare for a module to be specific and depend on a system, and at times the system version is relevant to the module version.

**Describe the solution you'd like**
Just like the shield that shows compatibility with the core version, a shield that shows `minimumSystemVersion` would be handy.

**Describe alternatives you've considered**
The following badge alternatives could be appropiate imo: _(using DnD5e v1.6.0 as example)_

\[**Supported Game System Version**  _1.6.0_\] (just like Core version one - System needs to be specified on a different shield)

\[**Supported DnD5e Version**  _1.6.0_\] (using the Short or Raw system name on the grey part)

**Comment by vigoren** [comment]
Thanks for the suggestion.

I have added a new option to the game system badge that will add the supported system version to the game system badge.

For example using the Hero Creation Tool the badge would look like:
![](https://img.shields.io/endpoint?url=https%3A%2F%2Ffoundryshields.com%2Fsystem%3FnameType%3Dfoundry%26showVersion%3D1%26url%3Dhttps%3A%2F%2Fraw.githubusercontent.com%2FHeroCreationLab%2Fhero-creation-tool%2Fmain%2Fsrc%2Fmodule.json)

The change is live so play around with it and let me know if you have other suggestions!

**Comment by ccjmk** [comment]
oh that looks super! I will definitely use it hahah

I kinda like the "shorter form" too but this is more in line with the rest, love it!
