### ISSUE TITLE
[FEATURE] Add the flat-square style as an option.

### ISSUE THREAD

**Issue by dirusulixes** [vigoren/foundryvtt-shields-io-badge#15]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the option for flat-square style badges

**Describe alternatives you've considered**
None

**Additional context**
A shield.io flat-square style example
![image](https://user-images.githubusercontent.com/5693623/165930750-7e547e3f-e8c3-4da1-b61a-8f419b872584.png)

**Comment by vigoren** [comment]
Hey, you can do this if you add `&style=flat-square` to the end of the generated URL.

That said it is a good idea to add a drop down selection to choose from Shield.IO's different style options

**Comment by vigoren** [comment]
Sorry this took so long a few other things on my plate but I have now released an update where you can pick the badge style from a drop down and it will apply it for you in the generated URL.
